### ISSUE TITLE
[建议]关于多选项卡切换的一个建议

### ISSUE THREAD

**Issue by SeaLoong** [smilecc/blive-intro#2]
生成简介时需要的“基本信息”中，“直播间地址”一项建议移除（因为在生成的HTML源代码中并没有发现其它需要使用到“直播间地址”的地方），并在生成的HTML源代码中
`<a href="直播间地址#can_node0" target="_self" ......>...</a>`
变更为
`<a href="#can_node0" target="_self" ......>...</a>`
这样可以防止因“直播间地址”填写不当（例如http与https的区别引发的问题）导致切换选项卡无效或需要再次点击才出现效果的问题
（因为不会PHP和Vue.js，所以没有发PR而是发Issue）

**Comment by smilecc** [comment]
谢谢你的建议。
其实这个是有作用的，如果在生成的时候为`<a href="#can_node0">`，但是提交到B站的简介之后，原本的`#can_node0`会被替换成`http://#can_node0`，这样就无法跳转到本页的锚点了，也就是说如果在href中写不带http为头的链接，会自动被B站加上`http;//`，暂时没有想到其他办法规避，只能用这种办法了。

**Comment by SeaLoong** [comment]
经测试，确实发现B站会替换，是我考虑不周，不好意思。
看你已经添加了获取用户直播信息的功能，这个问题应该已经不会再有了（虽然我觉得还是会在http和https上出问题，不过也只是需要重新加载一次而已）。
